#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------
set -e
runApplication decomposePar -allRegions
runApplication mpirun -np $(foamDictionary system/neutroRegion/decomposeParDict -entry numberOfSubdomains -value) GeN-Foam -parallel
runApplication reconstructPar -allRegions 
